Fix model validation, add CI
dbt-labs/dbt-jsonschema pull request #16
Opened 2022-09-13 21:29 UTC by kochalex

When trying to use these schemas in a CI workflow with our DBT project, I ran into a few errors with the JSON schema documents with both [Ajv](https://ajv.js.org/) and [jsonschema](https://python-jsonschema.readthedocs.io/en/stable/).

This has a couple of fixes that allowed the schemas themselves to be validated as draft 7. (I used draft 7 since it's the most common from my experience, but it might also be good to add a `$schema` entry to the files). There's also a sample GitHub Actions CI workflow that tests using ajv-cli:
1. If the schema files pass draft7
2. Testing a simple `dbt_project.yml` and `model.yml` file generated with `dbt init`.

Here's a run on my fork: https://github.com/kochalex/dbt-jsonschema/actions/runs/3048375813

<img width="828" alt="Screen Shot 2022-09-13 at 4 22 48 PM" src="https://user-images.githubusercontent.com/3217653/190011754-7b686306-1602-4fd9-a09c-5c20324480c4.png">

Separately, are there any plans for DBT to publish these schemas in a registry like https://schemas.getdbt.com/ or have them officially part of DBT?

I've pointed my VS Code at these updated files and our project's YAML files validate ok, but it should be noted that the existing files also seemed to work ok with the VS Code YAML extension, it was just the CI cases that failed (with two separate validators). I know CI is not the intended use case here. 😸

2022-09-13 21:29 UTC, kochalex commented on schemas/dbt_project.json
> +                    "pattern": "\\{\\{.*\\}\\}"
Per https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

2022-09-19 01:43 UTC, joellabes requested changes
This is awesome @kochalex! Thanks for doing this. 

I'm happy with schema version 7 if that's the default - I skipped on picking a version because I wasn't sure what the right one was, and it seemed to work without specifying one 😬 if you want to add that to these files as well I'd be happy to include it in this PR? 

Otherwise, just two pedantic changes around capitalisation (or lack thereof) of dbt. 

Such a good idea to put some CI on this, json is fiddly at the best of times.

2022-09-19 01:43 UTC, joellabes commented on tests/dbt_project.yml
> +# this file was generated with dbt init with DBT 1.2.1
```suggestion
# this file was generated with dbt init with dbt 1.2.1
```

dbt is always lowercase ;)

2022-09-19 01:43 UTC, joellabes commented on tests/schema.yml
> +# this file was generated with dbt init with DBT 1.2.1
```suggestion
# this file was generated with dbt init with dbt 1.2.1
```

Same here

2022-09-19 01:45 UTC, joellabes commented
> Separately, are there any plans for DBT to publish these schemas in a registry like https://schemas.getdbt.com/ or have them officially part of DBT?

Not yet, but over time as they get more robust it's not out of the question! We're also thinking about listing on schemastore, but that has some tradeoffs (see #3)

2022-09-19 16:55 UTC, kochalex commented
Ok, I've made the changes (caps and adding in `$schema`), would you like me to cleanup & squash the history on this?

2022-09-19 19:36 UTC, joellabes approved these changes

2022-09-19 19:36 UTC, joellabes commented
@kochalex we squash and merge so it's all good! Thank you for doing this 🌟

2022-09-19 19:36 UTC, merged