Add transient option to node configurations
dbt-labs/dbt-jsonschema pull request #48
Opened 2023-02-22 17:29 UTC by dwreeves

The Snowflake adapter allows for `+transient: [boolean]` as a configuration option:

See docs here: https://docs.getdbt.com/reference/resource-configs/snowflake-configs

Docs example:

```yaml
name: my_project

...

models:
  +transient: false
  my_project:
    ...
```

This pull request adds `+transient` as a supported attribute in the JSONSchema for node configurations.

I also confirmed that it is a `boolean` and not a `#/$defs/boolean_or_jinja_string`, i.e. `"{{ True }}"` renders as a string literal in the `manifest.json`, not as `true`.

2023-02-25 02:16 UTC, joellabes requested changes
Hey @dwreeves, thanks for opening this! Jinja strings can be converted to booleans using the as_bool filter: https://docs.getdbt.com/reference/dbt-jinja-functions/as_bool

This means that this property should also be a bool_or_jinja _string please!

2023-02-25 02:24 UTC, dwreeves commented
@joellabes Ah! Learned something new about dbt.

Made the requested change, although it means the description has to go, unless you want to do something like `{"allOf": [{"$ref": "#/$defs/string_or_array_of_strings"}], "description": "..."}`.

2023-03-15 03:36 UTC, joellabes commented
@dwreeves sorry for the delay getting back to you! I don't _think_ that's right - wouldn't it behave the same as https://github.com/dbt-labs/dbt-jsonschema/blob/main/schemas/dbt_project.json#L343-L347 where you can have a ref and then extend it with extra context?

2023-03-15 03:54 UTC, dwreeves commented
Ah, can you do that? I am not well versed enough at JSONSchema to know if that works. I was basing my assumption off [googling for various things](https://stackoverflow.com/questions/66262319/how-do-i-use-an-extended-definition-and-not-allow-additional-properties-in-a-way) and sort of half-following what others were saying.

It seems in the earliest draft of JSONSchema this would not have been supported, and frankly I'm not entirely following the discussions I'm reading on how this has changed over time.

>    An object schema with a "$ref" property MUST be interpreted as a
   "$ref" reference.  The value of the "$ref" property MUST be a URI
   Reference.  Resolved against the current URI base, it identifies the
   URI of a schema to use.  All other properties in a "$ref" object MUST
   be ignored.

Still, regardless of whether it works or not to just add the description, I don't know if I want to be the first person to add a `description` attribute to an object with a `$ref` property in this JSON.

So, is it OK if we leave the description out? 😬 Or do you want it in still?

2023-03-15 04:04 UTC, joellabes commented
Hmmmm that stack overflow post is pretty definitive! I also don't know a ton about JSON schema - I've picked up the basics from developing this repo but not an expert. 

I think that for now let's leave the description out, and I'll do some experimenting some other time

2023-03-15 04:05 UTC, joellabes approved these changes

2023-03-15 04:05 UTC, merged